# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangowang', '0005_daydown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gitpush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgsrc', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'gitpush',
            },
        ),
    ]
