# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangowang', '0006_gitpush'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goodlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=30)),
                ('goodsname', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('oldprice', models.FloatField()),
            ],
            options={
                'db_table': 'Goodlists',
            },
        ),
    ]
