# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-09 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangowang', '0008_auto_20181109_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydowndetail',
            name='bigimg1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='bigimg2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='bigimg3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='bigimg4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='dtbgimg1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='dtbgimg2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='dtbgimg3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='dtbgimg4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='dtbgimg5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='dtbgimg6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='dtbgimg7',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='dtbgimg8',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='evaluate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='hint',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='middleimg1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='middleimg2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='middleimg3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='middleimg4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='original',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='repertory',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='shopname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='smallimg1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='smallimg2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='smallimg3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='smallimg4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='daydowndetail',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
