# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hangowang', '0009_auto_20181109_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=50, null=True)),
                ('imgsrc', models.CharField(max_length=50)),
                ('middleimg1', models.CharField(max_length=50, null=True)),
                ('middleimg2', models.CharField(max_length=50, null=True)),
                ('middleimg3', models.CharField(max_length=50, null=True)),
                ('middleimg4', models.CharField(max_length=50, null=True)),
                ('smallimg1', models.CharField(max_length=50, null=True)),
                ('smallimg2', models.CharField(max_length=50, null=True)),
                ('smallimg3', models.CharField(max_length=50, null=True)),
                ('smallimg4', models.CharField(max_length=50, null=True)),
                ('bigimg1', models.CharField(max_length=50, null=True)),
                ('bigimg2', models.CharField(max_length=50, null=True)),
                ('bigimg3', models.CharField(max_length=50, null=True)),
                ('bigimg4', models.CharField(max_length=50, null=True)),
                ('dtbgimg1', models.CharField(max_length=50, null=True)),
                ('dtbgimg2', models.CharField(max_length=50, null=True)),
                ('dtbgimg3', models.CharField(max_length=50, null=True)),
                ('dtbgimg4', models.CharField(max_length=50, null=True)),
                ('dtbgimg5', models.CharField(max_length=50, null=True)),
                ('dtbgimg6', models.CharField(max_length=50, null=True)),
                ('dtbgimg7', models.CharField(max_length=50, null=True)),
                ('dtbgimg8', models.CharField(max_length=50, null=True)),
                ('hint', models.CharField(max_length=50, null=True)),
                ('evaluate', models.CharField(max_length=10, null=True)),
                ('repertory', models.CharField(max_length=10, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('unit', models.CharField(max_length=10, null=True)),
                ('price', models.CharField(max_length=10, null=True)),
                ('original', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'Goods_Detail',
            },
        ),
        migrations.AlterField(
            model_name='goodlists',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='goodsdetail',
            name='Goods',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hangowang.Goodlists'),
        ),
    ]
